### ISSUE TITLE
Not reading mseed files

### ISSUE THREAD

**Issue by Helenseiv** [paddy-seismic/retreat#4]
Hy everyone,

I'm trying to run retreat with my data. I've already tried with the example data and everything went fine. 

I tried to run with my data via the GUI interface and also by the command line editing the file default_input_values.py, but both ways result in the same error. It seems like my directory is empty, and it doesn't. The error message is:

Starting logging: 2021-09-30 15:55:38
Fetching parameters
Target plot window length = 3600.00s
Amount of data to fetch each update = 600.00s

--------------------------

**Fetching initial data
Replay mode selected: using local files as data source
Using custom directory structure:
{network}.{station}..{channel}.{year}.{doy:03d}.mseed
Retrieving data from filesystem...
Error: Stream empty - please check your data source
Error retrieving data. Check input source
Stream start time =  2020-01-26T06:00:00.000000Z
Process realtime:
Traceback (most recent call last):
  File "/home/helena/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/helena/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/helena/anaconda3/retreat/retreat/realtime.py", line 39, in realtime
    st_end = update(timing, mydata, preproc, kwargs, to_plot, spectro, array_resp, logfile, st_end)
  File "/home/helena/anaconda3/retreat/retreat/update.py", line 253, in update
    st_sta = min([tr.stats.starttime for tr in st])
TypeError: 'NoneType' object is not iterable**

-------------------------------------------

I suspect that my problem comes from the name of my files, but I've been looking at them and don't find the issue.

Could someone help me?

Thank you,

Helena.

**Comment by Helenseiv** [comment]
Sorry, I fixed the above problem. I was not giving the .scnl file.

Retreat is now reading my files, but the problem I bumped now I certainly don't know where comes:

------------------------------
--------------------------

Fetching initial data
Replay mode selected: using local files as data source
Using custom directory structure:
{network}.{station}..{channel}.{year}.{doy:03d}.mseed
Retrieving data from filesystem...
Stream start time =  2020-01-26T06:00:00.000000Z
Trimming waveform
Importing inventory file:  /home/helena/anaconda3/retreat/retreat/example_data/stationsORCA.xml
Process realtime:
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/helena/anaconda3/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/helena/anaconda3/retreat/retreat/data/get_meta.py", line 53, in get_meta
    inv = read_inventory(mydata["inv_file"], format=mydata["inv_type"])
  File "/home/helena/anaconda3/lib/python3.8/site-packages/decorator.py", line 231, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/helena/anaconda3/lib/python3.8/site-packages/obspy/core/util/decorator.py", line 300, in _map_example_filename
    return func(*args, **kwargs)
  File "/home/helena/anaconda3/lib/python3.8/site-packages/obspy/core/inventory/inventory.py", line 88, in read_inventory
    return _generic_reader(path_or_file_object, _read, format=format,
  File "/home/helena/anaconda3/lib/python3.8/site-packages/obspy/core/util/base.py", line 702, in _generic_reader
    generic = callback_func(pathnames[0], **kwargs)
  File "/home/helena/anaconda3/lib/python3.8/site-packages/decorator.py", line 231, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/helena/anaconda3/lib/python3.8/site-packages/obspy/core/util/decorator.py", line 210, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/home/helena/anaconda3/lib/python3.8/site-packages/obspy/core/inventory/inventory.py", line 97, in _read
    inventory, format = _read_from_plugin('inventory', filename, format=format,
  File "/home/helena/anaconda3/lib/python3.8/site-packages/obspy/core/util/base.py", line 453, in _read_from_plugin
    format = format.upper()
AttributeError: 'list' object has no attribute 'upper'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/helena/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/helena/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/helena/anaconda3/retreat/retreat/realtime.py", line 39, in realtime
    st_end = update(timing, mydata, preproc, kwargs, to_plot, spectro, array_resp, logfile, st_end)
  File "/home/helena/anaconda3/retreat/retreat/update.py", line 267, in update
    inv = executor.submit(get_meta, mydata, logfile).result()
  File "/home/helena/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/helena/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
AttributeError: 'list' object has no attribute 'upper'
----------------------------


Thanks again,

Helena.
